on:
  schedule:
    - cron: 0 0 * * */5

name: PHP auto build
jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
            ref: main

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_ORG_USER }}
          password: ${{ secrets.DOCKER_ORG_PASS }}

      - name: Pull
        run: docker pull sirherobrine23/phpbinbuild:latest

      - name: Docker Copiler
        run: |
          cd phpBinsDocker/
          docker buildx build --tag sirherobrine23/phpbinbuild:latest --push --platform linux/amd64,linux/arm64 --file dockerfile .

      - name: Docker get Zip
        run: |
          cd phpBinsDocker/
          docker manifest inspect --verbose sirherobrine23/phpbinbuild:latest > /tmp/ubuntuDoc
          JsonID=0
          while true
          do
            manifest="$(cat /tmp/ubuntuDoc | jq -r ".[${JsonID}].Descriptor.digest")"
            if [ "${manifest}" == "null" ];then break;fi
            echo "docker run --rm -v $PWD:/tmp/out sirherobrine23/phpbinbuild:latest@$manifest"
            echo "docker run --rm -v $PWD:/tmp/out sirherobrine23/phpbinbuild:latest@$manifest" | bash
            JsonID="$(($JsonID + 1))"
          done


      - uses: actions/upload-artifact@v2
        with:
          name: Linux
          path: phpBinsDocker/*.zip
          retention-days: 1

  Windows:
    runs-on: windows-latest
    steps:
      - name: clone pmmp/php-build-scripts
        uses: actions/checkout@master
        with:
            ref: stable
            repository: pmmp/php-build-scripts

      - name: Wget Install
        run: choco install wget --no-progress

      - name: PHP Copiler
        env:
          VS_EDITION: Enterprise
          SOURCES_PATH: ${{ github.workspace }}\pocketmine-php-sdk
        shell: cmd
        run: windows-compile-vs.bat

      - name: PHP Zip bin
        run: |
          dir
          7z a Windows_x64_php.zip bin

      - name: Log
        run: type compile.log

      - uses: actions/upload-artifact@v2
        with:
          name: Windows
          path: "*.zip"
          retention-days: 1

  MacOS:
    runs-on: macos-latest
    steps:
      - name: Install Depedencied
        run: brew install libtool autoconf automake pkg-config bison re2c

      - name: clone pmmp/php-build-scripts
        uses: actions/checkout@master
        with:
            ref: stable
            repository: pmmp/php-build-scripts

      - name: PHP Copiler
        run: |
          export PATH="/usr/local/opt/bison/bin:$PATH"
          set -ex
          . compile.sh -t mac64 -f -u -g -l
          zip MacOS_$(uname -m | sed 's|86_||g')_php.zip -r bin/

      - uses: actions/upload-artifact@v2
        with:
          name: Macos
          path: MacOS_*.zip
          retention-days: 1

  Publish:
    runs-on: ubuntu-latest
    needs: [ Linux, Windows, MacOS ]
    steps:
      # Setup Node
      - name: Setup Node JS
        uses: actions/setup-node@v1
        with:
          node-version: 15.x

      # Download Files
      - name: Download Linux
        uses: actions/download-artifact@v2
        with:
          name: Linux
          path: /tmp/Bins

      - name: Downlaod Windows
        uses: actions/download-artifact@v2
        with:
          name: Windows
          path: /tmp/Bins

      - name: Downlaod MacOS
        uses: actions/download-artifact@v2
        with:
          name: Macos
          path: /tmp/Bins

      # Prepare files
      - name: Publish PHP files bin
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: PHP bins, ${{ github.run_id }}
          tag_name: ${{ github.run_id }}
          files: /tmp/Bins/*.zip
          body: |
            Windows users install the [Microsoft Visual C ++ 2017 Redistributable](https://aka.ms/vs/15/release/vc_redist.x64.exe)

      - uses: actions/checkout@master
        with:
            ref: main

      - name: Prepare JSon
        run: |
          cd workflows/
          npm install
          tag_name="${{ github.run_id }}" node php_get.js

      - name: Create Pull Request
        if: env.upload == 'true'
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Sever.json update
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: PHP_BIN_${{ github.run_id }}
          delete-branch: true
          base: main
          title: 'php_bin.json update, check update in ${{ github.run_id }}'
          body: |
            Update report
          labels: |
            PHP_Update
          team-reviewers: |
            owners
            maintainers
          draft: false
