on: 
  push:
    branches:
      - main
  schedule:
    - cron: 0 */4 * * *
name: Server.json auto update
jobs:
  json_update:
    name: Sever.json update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Node JS
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install Lynx
        run: |
          sudo apt update
          sudo apt install -y lynx curl

      - name: Install Node Packages
        run: npm install -d --no-save

      - name: Check Versions
        run: npm run find_new_version

      - name: Create Commit Files
        continue-on-error: true
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -F .commit_template.md
          git push
