on: 
  push:
    branches:
      - main
  schedule:
    - cron: 0 */3 * * *
name: Server.json auto update
jobs:
  json_update:
    name: Sever.json update
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node JS
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - uses: actions/checkout@master
        with:
          ref: main
      - name: Install lynx and Check Versions
        run: |
          sudo bash -c "apt update && apt install -y lynx curl" > /dev/null
          npm install --no-save -d
          node ./Server_Lints/lint_server.js

      - name: Commit Modifications
        continue-on-error: true
        run: |
          git config --global user.email 'github-actions@github.com'
          git config --global user.name 'github-actions[bot]'
          git config --global http.postBuffer 157286400 sslVerify=false
          git add .
          git commit -m "Update Server.json" -m "- bedrock Version: ${{ env.bedrock_version }}" -m "- java Version: ${{ env.java_version }}" -m "- PocketMine Version: ${{ env.pocketmine_version }}"
          git push
