





on: 
  push:
  schedule:
    - cron: 0 0 * * *
    - cron: 0 12 * * *
name: Server.json auto update
jobs:
  json_update:
    name: Sever.json update
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: ActionsRML/delete-workflow-runs@main
        with:
          retain_days: 2
      - name: install lynx
        run: sudo bash -c "apt update && apt install -y lynx"
      - name: Setup Node JS
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - uses: actions/checkout@master
      - name: Check
        run: cd workflows/ && node ./Server.js
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        continue-on-error: true
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Sever.json update
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: main
          delete-branch: true
          title: 'Server.json update, check update in ${{ github.run_id }}'
          body: |
            Update report
            - bedrock Version: ${{ env.bedrock_version }}
            - java Version: ${{ env.java_version }}
          labels: |
            Server_Update
          team-reviewers: |
            owners
            maintainers
          draft: false
