on: 
  push:
    branches:
      - main
  schedule:
    - cron: 0 */3 * * *
name: Server.json auto update
jobs:
  json_update:
    name: Sever.json update
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: GitRML/delete-workflow-runs@main
        with:
          retain_days: 2
          keep_minimum_runs: 1
      - name: install lynx
        run: sudo bash -c "apt update && apt install -y lynx"
      - name: Setup Node JS
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - uses: actions/checkout@master
        with:
            ref: main
      - name: Install Node Depedencies
        run: |
          cd workflows/ 
          npm i --no-save
      - name: Check Versions
        run: |
          cd workflows/ 
          node ./Server.js
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        continue-on-error: true
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Sever.json update
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: Server_${{ github.run_id }}
          delete-branch: true
          base: main
          title: 'Server.json update, check update in ${{ github.run_id }}'
          body: |
            Update report
            - bedrock Version: ${{ env.bedrock_version }}
            - java Version: ${{ env.java_version }}
            - PocketMine Version: ${{ env.pocketmine_version }}
          labels: |
            Server_Update
          team-reviewers: |
            owners
            maintainers
          draft: false

  bin_php:
    name: Update php_get.json
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node JS
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - uses: actions/checkout@master
        with:
            ref: main
      - name: Check PHP Versions
        run: |
          cd workflows/
          npm install
          tag_name="${{ github.run_id }}" node ./php_get.json

      - name: Publish PHP files bin
        if: '${{ env.upload}} === true'
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Bds Maneger Version ${{ env.BDS_VER }}
          tag_name: ${{ github.run_id }}
          files: 'php_files/*.zip'
          body: |
            
            ${{ env.COMMIT_ME }}